### ISSUE TITLE
Version 4 Support

### ISSUE THREAD

**Issue by chaojian-zhang** [sericaer/godot_table#3]
There are parsing errors when loading in Godot 4.

**Comment by EinRainerZufall** [comment]
hi @chaojian-zhang 
if you still want to use this plugin, you can use my fork, which I have adapted to Godot 4 https://github.com/EinRainerZufall/godot_table

**Comment by chaojian-zhang** [comment]
Thanks! I found for simple tables one can just use [Tree](https://docs.godotengine.org/en/stable/classes/class_tree.html).

**Comment by EinRainerZufall** [comment]
Ok, I didn't even know that, do you happen to have an example of how to do that?

**Comment by chaojian-zhang** [comment]
> Ok, I didn't even know that, do you happen to have an example of how to do that?

Yeah, here you are!
https://github.com/Charles-Zhang-Godot/Sample_TreeForDataGrid

**Comment by EinRainerZufall** [comment]
Thanks for that, I'll have a look at it soon

**Comment by sericaer** [comment]
> Thanks! I found for simple tables one can just use [Tree](https://docs.godotengine.org/en/stable/classes/class_tree.html).
Thank you for this demon，and I will learn tree control from it!

**Comment by sericaer** [comment]
> hi @chaojian-zhang if you still want to use this plugin, you can use my fork, which I have adapted to Godot 4 https://github.com/EinRainerZufall/godot_table

Thank you for adapting to Godot 4. Could you send a pull request?
